### ISSUE TITLE
cms/admin.lib.php

### ISSUE THREAD

**Issue by carrie0307** [delta/pragyan#229]
When I opened the site "cms/admin.lib.php" I got "403 Forbidden You are not authorized to access the page", but I think I've finished the installion of pragyan and I can open the "*.html" normally .Can you give some suggestion on why this happend?
And I want to test the vulnerabilities in "cms/admin.lib.php" locally for studying, which page should I open?

Thank you so much !!!

**Comment by ssundarraj** [comment]
@shravan97 PTAL

**Comment by shravan97** [comment]
@carrie0307 , "admin.lib.php" is more like a library that supports admin operations like modules administration, templates administration and user administration. In order to access the functionalities this provides, login to the cms with admin creds and use the route "/+admin". So, if you wanna fiddle around with and find vulnerabilities in the admin functionalities, then use one of the forms in "/+admin".

And, the reason why the resource "admin.lib.php" can't be accessed is that, the rewrite rules in [htaccess-dist](https://github.com/delta/pragyan/blob/af55413edaeb90e7ecb544cf9983ff979803a503/htaccess-dist#L67) say that, url should be rewritten to "/home/some_route" only when "/some_route" doesn't point to a file/resource. Otherwise, it redirects you to the resource itself. 

In your case, "admin.lib.php" is a valid resource. So, it'd  try to open the resource. And, when you look into that file, the constant "__PRAGYAN_CMS" is not declared because you're accessing this directly through its url and not through a script. So, this would only echo out "403 Forbidden".

I hope this answers your questions. I'll close this issue soon if you don't have anything else to ask

**Comment by carrie0307** [comment]
Thank you so much for your reply!

 But I still can't login in with admin creds because I can't find the page which is designed for admin to login. I tried to find the admin login page with the route "pragyan/home/+admin",but I got the message "  You do not have the permissions to view this page. " And when I tried " pragyan/cms/+admin" I got "The requested page does not exist.“

Could you please tell me how can I login in witeh admin cred?

Sorry to bother you and thank you very much !

**Comment by carrie0307** [comment]
Thank you so much for your reply!

 But I still can't login in with admin creds because I can't find the page which is designed for admin to login. I tried to find the admin login page with the route "pragyan/home/+admin",but I got the message "  You do not have the permissions to view this page. " And when I tried " pragyan/cms/+admin" I got "The requested page does not exist.“

Could you please tell me how can I login in witeh admin cred?

Sorry to bother you and thank you very much !

**Comment by carrie0307** [comment]
Besieds, when I visit " pragyan/home/+admin ", I also can see "Try logging in?". And when I click it get access to the login page, I can only login with cred of  ordinary user. Although I input the admin information which I set when installing, I can't login as the admin.

**Comment by shravan97** [comment]
@carrie0307 , whosoever configured the cms would be admin by default. If you configured the cms you would definitely be admin. Otherwise, the admin will have to give permissions to the respective user in order for the user to become admin.

And there is no such thing here as "admin" login. Even the admin has to login using the same user creds that he/she has. And login happens through the route "/+login". So, the page that you got on "pragyan/home/+admin" might have been because you weren't logged in. And if you're sure that you'd logged in, then you don't have admin permissions and you'll have to contact your admin for permissions.

**Comment by carrie0307** [comment]
But I can only login  as ordinary user through the route "/+login". Although I input the admin information which I set when installing, I can't login as the admin. Did the mean there is something wrong with my installation or  something else? 

Thanks for your reply !

**Comment by carrie0307** [comment]
I've solved the problem and you can close this issue.

Thank you for your help  !

May you have a good day!

**Comment by shravan97** [comment]
@carrie0307 , sorry for the late response. I'm glad that you found the solution. Thank you for your interest in Pragyan Cms ! 😄
